[run]
watch_all = true
watch_dirs = ["cmd", "pkg"]
watch_exts = [".go"]
ignore = [".git"]
ignore_files = []
build_delay = 1500
interrupt_timout = 15
graceful_kill = false

init_cmds = [
  ["make", "build"],
  [
    "./bin/terrastate",
    "--log-level",
    "debug",
    "server",
    "--general-username",
    "terrastate",
    "--general-password",
    "terrastate"
  ]
]

cmds = [
  ["make", "build"],
  [
    "./bin/terrastate",
    "--log-level",
    "debug",
    "server",
    "--general-username",
    "terrastate",
    "--general-password",
    "terrastate"
  ]
]
